run:
  timeout: 5m

linters-settings:
  # gocritic:
  #   enabled-tags:
  #   - performance
  importas:
    no-unaliased: true
  lll:
    line-length: 200

  misspell:
    locale: US
  staticcheck:
    go: "1.20"

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - revive # replacement for golint
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
