run:
  timeout: 5m

linters-settings:
  lll:
    line-length: 200
  misspell:
    locale: US
  staticcheck:
    go: "1.21"

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - gci
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
