# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlAi < Formula
  desc "kubectl-ai is a kubectl plugin to generate and apply Kubernetes manifests using OpenAI GPT."
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sozercan/kubectl-ai/releases/download/v0.0.9/kubectl-ai_darwin_arm64.tar.gz"
      sha256 "f1d834181296005ec7d0fedb08f5810ccae5e6115dfc6eddd5fd93ae144322cc"

      def install
        bin.install "kubectl-ai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sozercan/kubectl-ai/releases/download/v0.0.9/kubectl-ai_darwin_amd64.tar.gz"
      sha256 "b4a3ea25b23200eeaf92514482b326c2bed170f7ea273dced23f83f9ee38dcdd"

      def install
        bin.install "kubectl-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sozercan/kubectl-ai/releases/download/v0.0.9/kubectl-ai_linux_arm64.tar.gz"
      sha256 "2e635ab6441326f85955f56e60bc5be93254eeebf4224f488f6265e1743364cc"

      def install
        bin.install "kubectl-ai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sozercan/kubectl-ai/releases/download/v0.0.9/kubectl-ai_linux_amd64.tar.gz"
      sha256 "04671ad847123ce0001e6a497c51b88e0e474be6b09aa5071e5c1f09b11cc1ba"

      def install
        bin.install "kubectl-ai"
      end
    end
  end

  def caveats
    <<~EOS
      This plugin requires an OpenAI key.
    EOS
  end
end
