name: Request
description: Request a new feature or propose an enhancement to Kubectl AI
title: "[REQ] <title>"
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Please search to see if an issue already exists for your request before continuing.
  - type: dropdown
    attributes:
      label: What kind of request is this?
      multiple: false
      options:
        - New feature
        - Improvement of existing experience
        - Other
  - type: textarea
    attributes:
      label: What is your request or suggestion?
      placeholder: |
        e.g. I would like Kubectl AI to add this <feature> so that I can use it in my <scenario>.
        e.g. When using Kubectl AI the <current behavior> has this <limitation> and it would be better if it has this <improvement>.
  - type: checkboxes
    id: idea
    attributes:
      label: "Are you willing to submit PRs to contribute to this feature request?"
      options:
        - label: Yes, I am willing to implement it.
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a request!