name: build-and-test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: "1.20"

      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build and test
        run: make test bin
